# Generated by Django 3.2.7 on 2021-10-09 12:46

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_1', models.CharField(blank=True, max_length=20, verbose_name='телефон 1')),
                ('phone_2', models.CharField(blank=True, max_length=20, verbose_name='телефон 1')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('schedule', models.CharField(blank=True, max_length=200, verbose_name='График работы')),
                ('map', django_quill.fields.QuillField(blank=True, verbose_name='Карта')),
            ],
        ),
    ]
