# Generated by Django 3.2.7 on 2021-10-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20211009_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_1',
            field=models.CharField(max_length=20, verbose_name='телефон 1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='schedule',
            field=models.CharField(max_length=200, verbose_name='График работы'),
        ),
    ]
