# Generated by Django 3.2.7 on 2021-10-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20211009_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='map',
            field=models.TextField(verbose_name='iframe карты'),
        ),
    ]
