# Generated by Django 3.2.7 on 2021-10-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='телефон 2'),
        ),
    ]
