# Generated by Django 3.2.7 on 2021-11-28 13:04

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='слаг')),
                ('content', django_quill.fields.QuillField(blank=True, verbose_name='контент')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='изображение')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='сертификат')),
                ('top', models.BooleanField(blank=True, default=False, null=True, verbose_name='в топе')),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'производители',
                'ordering': ('title',),
            },
        ),
    ]
