# Generated by Django 3.2.7 on 2021-11-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textpages2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section2',
            name='title',
        ),
    ]
