# Generated by Django 3.2.7 on 2021-11-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textpages2', '0002_remove_section2_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section2',
            name='image',
        ),
        migrations.AddField(
            model_name='section2',
            name='title',
            field=models.CharField(default=2, max_length=200, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
