# Generated by Django 3.2.7 on 2021-11-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textpages2', '0004_alter_page2_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page2',
            options={'ordering': ['id'], 'verbose_name': 'Страница ИТ', 'verbose_name_plural': 'Страница ИТ'},
        ),
        migrations.AlterModelOptions(
            name='section2',
            options={'ordering': ['pk']},
        ),
    ]
