# Generated by Django 3.2.7 on 2021-11-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textpages2', '0005_auto_20211107_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page2',
            options={'ordering': ['id'], 'verbose_name': 'Страница ИТ-Услуг', 'verbose_name_plural': 'Страница ИТ-услуг'},
        ),
    ]
