# Generated by Django 3.2.7 on 2021-10-09 11:43

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг')),
                ('thumbnail', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Иконка')),
                ('content', django_quill.fields.QuillField(verbose_name='Контент')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
