# Generated by Django 3.2.7 on 2021-10-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211009_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='thumbnail',
            field=models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Иконка (черного цвета)'),
        ),
    ]
