# Generated by Django 3.2.7 on 2021-11-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница ИБ', 'verbose_name_plural': 'Страница ИБ'},
        ),
    ]
