# Generated by Django 3.2.7 on 2021-11-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textpages', '0002_alter_page_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-pk'], 'verbose_name': 'Страница ИБ', 'verbose_name_plural': 'Страница ИБ'},
        ),
    ]
