# Generated by Django 3.2.7 on 2021-11-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textpages', '0003_alter_page_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['id'], 'verbose_name': 'Страница ИБ', 'verbose_name_plural': 'Страница ИБ'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['pk']},
        ),
    ]
