# Generated by Django 3.2.7 on 2021-10-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0016_alter_product_accessories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Настройки сайта', editable=False, max_length=30)),
                ('main_product', models.ManyToManyField(to='catalog.Product')),
            ],
        ),
    ]
