# Generated by Django 3.2.7 on 2021-10-10 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20211009_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='изображение')),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.config')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
                'ordering': ('created',),
            },
        ),
    ]
