# Generated by Django 3.2.7 on 2021-11-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20211010_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Логотип в футере'),
        ),
        migrations.AddField(
            model_name='config',
            name='header_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Логотип в шапке'),
        ),
    ]
