# Generated by Django 3.2.7 on 2021-10-08 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reply_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.review', verbose_name='ответ на'),
        ),
    ]
