# Generated by Django 3.2.7 on 2021-10-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20211008_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reply_to',
        ),
    ]
