# Generated by Django 3.2.7 on 2021-09-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_price_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product'),
        ),
    ]
