# Generated by Django 3.2.7 on 2021-09-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='excerpt',
            field=models.TextField(blank=True, null=True, verbose_name='краткое описание'),
        ),
    ]
