# Generated by Django 3.2.7 on 2021-09-25 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210925_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='slug',
        ),
        migrations.AddField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kit',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.attribute', verbose_name='атрибут'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='value',
            field=models.CharField(max_length=100, verbose_name='значение'),
        ),
    ]
