# Generated by Django 3.2.7 on 2021-09-26 09:04

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
