# Generated by Django 3.2.7 on 2021-09-26 09:18

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_description_product_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
