# Generated by Django 3.2.7 on 2021-09-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accessories',
            field=models.ManyToManyField(blank=True, null=True, related_name='_catalog_product_accessories_+', to='catalog.Product', verbose_name='аксесуары'),
        ),
    ]
