# Generated by Django 3.2.7 on 2021-09-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_accessories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ('created',), 'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
        migrations.AlterField(
            model_name='product',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='_catalog_product_accessories_+', to='catalog.Product', verbose_name='аксесуары'),
        ),
    ]
