# Generated by Django 3.2.7 on 2021-09-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20210929_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_current',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Текущая цена'),
        ),
    ]
