# Generated by Django 3.2.7 on 2021-10-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='accessories',
            field=models.ManyToManyField(blank=True, help_text='Выберете категорию или несколько категорий товаров,                                          в которой находятся аксесуары для товара', to='catalog.Category', verbose_name='аксесуары'),
        ),
    ]
