# Generated by Django 3.2.7 on 2021-10-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales',
            field=models.PositiveIntegerField(verbose_name='количество продаж'),
        ),
    ]
