# Generated by Django 3.2.7 on 2021-10-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='title',
            field=models.CharField(blank=True, default='Оплата и доставка', editable=False, max_length=40, verbose_name='Заголовок'),
        ),
    ]
