# Generated by Django 3.2.7 on 2021-10-10 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_delivery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='changed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Изменено'),
        ),
    ]
