# Generated by Django 3.2.7 on 2021-10-10 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_product_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='catalog.product'),
        ),
    ]
