# Generated by Django 3.2.7 on 2021-10-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='название'),
        ),
    ]
