# Generated by Django 3.2.7 on 2021-10-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='количество продаж'),
        ),
    ]
