# Generated by Django 3.2.7 on 2021-10-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_alter_product_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
