# Generated by Django 3.2.7 on 2021-11-04 12:23

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_alter_galleryimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
