# Generated by Django 3.2.7 on 2021-11-04 12:26

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_alter_product_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='длинное описание'),
        ),
    ]
