# Generated by Django 3.2.7 on 2021-11-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20211104_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='public',
            field=models.BooleanField(default=False, verbose_name='публичный?'),
        ),
    ]
