# Generated by Django 3.2.7 on 2021-11-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_attribute_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='public',
            field=models.BooleanField(default=True, verbose_name='публичный?'),
        ),
    ]
