# Generated by Django 3.2.7 on 2021-11-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_alter_attribute_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='изображение'),
        ),
    ]
