# Generated by Django 3.2.7 on 2021-11-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_auto_20211111_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product'),
        ),
    ]
