# Generated by Django 3.2.7 on 2021-12-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_auto_20211206_1821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Tag',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы (для вариаций)'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='group',
            new_name='tag',
        ),
    ]
