# Generated by Django 3.2.7 on 2021-12-06 18:25

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_alter_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='licence_schemes',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='схемы лицензии'),
        ),
    ]
