# Generated by Django 3.2.7 on 2021-10-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('Самовывоз со склада в Москве', 'Самовывоз со склада в Москве'), ('Бесплатная доставка', 'Бесплатная доставка')], default=0, max_length=200, verbose_name='Доставка'),
            preserve_default=False,
        ),
    ]
