# Generated by Django 3.2.7 on 2021-10-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_shipping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
