# Generated by Django 3.2.7 on 2021-10-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default='YRF3C5RFICWISEWFR6GJ', help_text='Для теста можете     использовать токен: YRF3C5RFICWISEWFR6GJ', max_length=500, null=True, verbose_name='API-token сбербанка')),
            ],
            options={
                'verbose_name': 'Токен оплаты',
                'verbose_name_plural': 'Токены оплаты',
            },
        ),
    ]
